[package]
name = "phf_macros"
version = "0.7.24"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Macros to generate types in the phf crate"
repository = "https://github.com/sfackler/rust-phf"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
proc-macro2 = "0.4"
proc-macro-hack = "0.5.4"

phf_generator = { version = "0.7.24", path = "../phf_generator" }
phf_shared = { version = "0.7.24", path = "../phf_shared" }

[dev-dependencies]
trybuild = "1.0"
phf = { version = "0.7", path = "../phf", features = ["macros", "unicase"] }
unicase = "2.4.0"
